version: '3.8'

services:
  app:
    build: .
    container_name: college_schedule_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./server:/app/server
      - ./static:/app/static
    command: python server/run_all.py
